---
output: html_document
---

Hello and welcome.  

Let’s start like this: mixed models also go by the name of multilevel models, hierarchical models, mixed effects models, mixed regression models, random coefficient models.  
Many textbooks abound on this topic. If you dig in a bit you’ll see that some names surface up frequently: Tom Snjiders, Joop Hox, Harvey Goldstein, Stephen Raudenbush to name a few. Most of the theoretical stuff I present here has been taken from Snijders TAB & Bosker RJ (2012). [Multilevel Analysis: An Introduction to Basic and Advanced Multilevel Modeling]. The rest is bits and pieces from here and there. With time I will add references and corresponding links in the text so you can further your explorations of mixed models.  
Another book that I like and that you might want to take a look at is: Heck RH, Thomas SL & Tabata LN (2014). [Multilevel and Longitudinal Modeling with SPSS](https://www.routledge.com/Multilevel-and-Longitudinal-Modeling-with-IBM-SPSS-2nd-Edition/Heck-Thomas-Tabata/p/book/9780415817110). It’s a really nice book to get around mixed models in SPSS. It’s filled with diagrams taking you every step of the way.  

You'll be seeing a lot images and gif files (on and endless mind-disturbing loop) illustrating how to use IBM SPSS to run mixed models. These images and gifs refer to IBM SPSS version 25. Different SPSS versions may show different dialog boxes. I don’t expect these differences to be very dramatic, but even if they are, with a bit of patience you’ll make SPSS do what you want. Remember: computers are stupid machines that just do what you tell them to do!  

This tutorial is an ongoing project. It will get better with time. Suggestions, comments and corrections are really welcomed. You can email me at joaordaniel at gmail.com, or if you know your way around github do your push and pulls at https://github.com/joaordaniel/stats.  
I’ve tried as much as I can to put things in lay terms without sacrificing too much the mathematical truth behind all this… Enjoy!

